services:
  db:
    image: postgres:15-alpine
    container_name: booking_postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: booking_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: booking_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/project/backend/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data: